-- SELECT F.Title
-- FROM RATING AS R NATURAL JOIN FILM AS F
-- WHERE F.Year >= 1990 AND F.Year <= 2000
-- GROUP BY R.FilmID
-- HAVING AVG(R.Rating) >= 7

SELECT MIN(U.Age) AS MinAge
FROM USER AS U NATURAL JOIN RATING AS R NATURAL JOIN FILM AS F
WHERE R.Rating > 8 AND F.Title = 'Blade Runner'